name: invoice
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  ui_components:
    path: ../ui_components
  flutter_svg: 2.0.6
  flutter_gen: ^5.4.0
  shared_preferences: ^2.2.2
  go_router: ^10.1.2
  flutter_riverpod: ^2.5.1
  hooks_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  flutter_hooks: ^0.20.5
  collection: ^1.18.0
  intl: ^0.19.0
  reactive_forms: ^16.1.1
  reactive_forms_annotations: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.8
  custom_lint: ^0.6.2
  riverpod_lint: ^2.3.10
  reactive_forms_generator: ^4.5.2
  golden_toolkit: ^0.15.0

flutter_gen:
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  fonts:
    - family: LeagueSpartan
      fonts:
        - asset: assets/fonts/league_spartan_bold.ttf
          weight: 500
        - asset: assets/fonts/league_spartan_medium.ttf
          weight: 600
  assets:
    - assets/icons/
    - assets/images/
